language: bash
services: docker

env:
  global:
    - DOCKER_BUILD=awareoss/newrelic-dotnet
    - NEW_RELIC_VERSION=8.15.455.0
    - NEW_RELIC_URL=https://download.newrelic.com/dot_net_agent/previous_releases/8.15.445.0/newrelic-netcore20-agent_${NEW_RELIC_VERSION}_amd64.tar.gz
  matrix:
    - DOCKERFILE=2.2/runtime/Dockerfile
      TAG=2.2
    - DOCKERFILE=2.2/runtime/alpine/Dockerfile
      TAG=2.2-alpine
    - DOCKERFILE=2.2/aspnetcore-runtime/alpine/Dockerfile
      TAG=2.2-alpine
    - DOCKERFILE=2.2/aspnetcore-runtime/alpine/Dockerfile
      TAG=2.2-alpine
script:
  - docker build -t ${DOCKER_BUILD}:${TAG} $(dirname ${DOCKERFILE})
after_script:
  - docker images
branches:
  only:
    - master