sudo: 'required'
services:
  - docker

env:
  global:
    - NEW_RELIC_VERSION="8.17.438.0"
    - NEW_RELIC_URL="https://download.newrelic.com/dot_net_agent/previous_releases/8.17.438.0/newrelic-netcore20-agent_8.17.438.0_amd64.tar.gz"
    - IMAGE_NAME="awareoss/newrelic-dotnet"
  matrix:
<<<<<<< HEAD
    - IMAGE_TAG="2.2" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/" IMAGE_RUNTIME="aspnet"
    - IMAGE_TAG="2.2" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/runtime" IMAGE_RUNTIME="runtime"
    - IMAGE_TAG="3.0" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/aspnet" IMAGE_RUNTIME="aspnet"
    - IMAGE_TAG="3.0" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/runtime" IMAGE_RUNTIME="runtime"
    - IMAGE_TAG="2.2-alpine" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/" IMAGE_RUNTIME="aspnet"
    - IMAGE_TAG="2.2-alpine" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/" IMAGE_RUNTIME="runtime"
    - IMAGE_TAG="3.0-alpine" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/" IMAGE_RUNTIME="aspnet"
    - IMAGE_TAG="3.0-alpine" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/" IMAGE_RUNTIME="runtime"
=======
    - IMAGE_TAG="2.2" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/aspnet"
    - IMAGE_TAG="2.2" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/runtime"
    - IMAGE_TAG="3.0" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/aspnet"
    - IMAGE_TAG="3.0" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/runtime"
    - IMAGE_TAG="2.2-alpine" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/aspnet"
    - IMAGE_TAG="2.2-alpine" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/runtime"
    - IMAGE_TAG="3.0-alpine" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/aspnet"
    - IMAGE_TAG="3.0-alpine" DOCKERFILE_PATH="Dockerfile.deb" CONTAINER_IMAGE="mcr.microsoft.com/dotnet/core/runtime"
>>>>>>> c7f96302a51a664564dff8f52e98b12bdb2fe42b

jobs:
  allow_failures:
    - env:
      - IMAGE_TAG="2.2"
      - DOCKERFILE_PATH="Dockerfile.alpine"
    - env:
      - IMAGE_TAG="3.0"
      - DOCKERFILE_PATH="Dockerfile.alpine"
    - env:
      - IMAGE_TAG="2.2-alpine"
      - DOCKERFILE_PATH="Dockerfile.deb"
    - env:
      - IMAGE_TAG="3.0-alpine"
      - DOCKERFILE_PATH="Dockerfile.deb"

script:
  - bash build-image.sh