sudo: 'required'
services:
  - docker

env:
  global:
    - NEW_RELIC_VERSION="8.17.438.0"
    - NEW_RELIC_URL="https://download.newrelic.com/dot_net_agent/previous_releases/8.17.438.0/newrelic-netcore20-agent_8.17.438.0_amd64.tar.gz"
    - IMAGE_NAME="awareoss/newrelic-dotnet"

script:
  - bash build-image.sh Dockerfile.deb mcr.microsoft.com/dotnet/core/aspnet 2.2
  - bash build-image.sh Dockerfile.deb mcr.microsoft.com/dotnet/core/runtime 2.2
  - bash build-image.sh Dockerfile.alpine mcr.microsoft.com/dotnet/core/aspnet 2.2-alpine
  - bash build-image.sh Dockerfile.alpine mcr.microsoft.com/dotnet/core/runtime 2.2-alpine
  - bash build-image.sh Dockerfile.deb mcr.microsoft.com/dotnet/core/aspnet 3.0
  - bash build-image.sh Dockerfile.deb mcr.microsoft.com/dotnet/core/runtime 3.0
  - bash build-image.sh Dockerfile.alpine mcr.microsoft.com/dotnet/core/aspnet 3.0-alpine
  - bash build-image.sh Dockerfile.alpine mcr.microsoft.com/dotnet/core/runtime 3.0-alpine